Changed tutorial names
MAAP-Project/maap-documentation pull request #200
Opened 2023-05-18 21:56 UTC by smk0033

Changed the science tutorial names. Ignore all of the other changes made to HLS for now, I started working on other tickets with that one. I also adjusted some of the file names

2023-05-18 22:09 UTC, wildintellect requested changes
GEDI_02B and GEDI L2B are the same thing. For consistency we need to have the same naming style (I prefer the L2A L2B style).

- Do the notebooks really need tutorial in their name?
- What's the difference between the 02B and L2B notebooks?

As noted in slack, the HLS notebook changes should be removed from this branch before we can approve as it's not part of the task/ticket.

2023-05-18 22:21 UTC, jjfrench commented
@wildintellect, looks like Aimee's (02B) is a tutorial on using the STAC catalog while Nathan's (L2B) is using NASA CMR search

2023-05-18 22:26 UTC, wildintellect commented
Are we keeping 02B in MAAP STAC @abarciauskas-bgse? I think we removed it as a duplicate of NASA CMR, so delist or delete the notebook?

2023-05-18 22:32 UTC, rtapella approved these changes
Superficially this is fine. I don’t know enough about the details to comment more.

2023-05-19 14:20 UTC, smk0033 commented
@wildintellect I'll switch over the GEDI tutorials to use L instead of 0! As for the two L2B ones, is the CMR one going to be deleted as you suggested above? If not, I'll have to add something to differentiate the two (Like GEDI_L2B_stac and GEDI_L2B_cmr?)

2023-05-19 14:21 UTC, smk0033 commented
I'll also go ahead and remove "tutorial" from the files names so they'll just be the datasets

2023-05-19 20:50 UTC, smk0033 commented
New commit. Left GEDI_02B as-is in case it does get deleted, if not then I'll have to readjust the names to separate the GEDI_L2Bs. I also think I fixed the HLS file?

2023-05-19 23:37 UTC, wildintellect commented on docs/source/science/GEDI/GEDI_02B.ipynb
Should we hide this from the Navigation if it doesn't actually work anymore?

2023-05-19 23:40 UTC, wildintellect commented on docs/source/science/GEDI/GEDI_L4A.ipynb
Change Plot to Visualize to be consistent with other notebooks?

2023-05-19 23:41 UTC, wildintellect commented on docs/source/science/GEDI/GEDI_L4B.ipynb
This is not a blocker on this PR, but this tutorial should be updated to use L4B granules directly from Earth Data Cloud, it should not 'download'.

2023-05-19 23:44 UTC, wildintellect commented on docs/source/science/HLS/HLSL30.ipynb
I'm not sure Visualize is the correct term for this title - Composite the original term is much closer to the science term to take mulitple rasters over the same place and combine them. In this case many files are being combined to find the max NDVI for each pixel over the time period selected.

2023-05-22 16:08 UTC, smk0033 commented on docs/source/science/GEDI/GEDI_02B.ipynb
That sounds good! Is there a way to do that using git in the terminal, or is that something we will do through Github itself?

2023-05-22 16:23 UTC, wildintellect commented on docs/source/science/GEDI/GEDI_02B.ipynb
The navigation is controlled by https://github.com/MAAP-Project/maap-documentation/blob/develop/docs/source/science_examples.rst just remove the line referencing the notebook and commit the change.

2023-05-22 16:42 UTC, smk0033 commented on docs/source/science/GEDI/GEDI_L4B.ipynb
That is noted! Since it's not a blocker on this PR, does it need to go ahead and be updated, or can I update when I go through the science tutorials and change the CMR/ops stuff?

2023-05-22 16:45 UTC, wildintellect commented on docs/source/science/GEDI/GEDI_L4B.ipynb
I would make a ticket specific for updating the notebook. This would correspond to when you review the notebooks for template consistency and will be working with 1 notebook at a time.

2023-05-22 18:15 UTC, smk0033 commented
Also updated GEDI_L4B to "Search and Visualize"

2023-05-22 23:36 UTC, wildintellect approved these changes

2023-05-23 15:42 UTC, merged