guide
MAAP-Project/maap-documentation pull request #459
Opened 2024-11-14 19:46 UTC by HarshiniGirish

@omshinde please look into it now. I have uploaded it again

2024-11-14 19:57 UTC, omshinde commented
Thank you. Reviewing the notebook now.

2024-11-14 20:11 UTC, omshinde commented on maapcopcguide (2).ipynb
> +{
<p>Change this to something like - Working with LiDAR Cloud Optimized Point Cloud (COPC) in MAAP</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/MAAP-Project/maap-documentation/pull/459/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='0'/>

2024-11-14 20:11 UTC, omshinde commented on maapcopcguide (2).ipynb
> +{
<p>&gt;<strong>Authors</strong>: Harshini Girish (UAH), Rajat Shinde (UAH), Alex Mandel (DevSeed), Jamison French (DevSeed), Brian Freitag (NASA MSFC), Sheyenne Kirkland (UAH)</p><p> </p><p>We can include Chuck, Henry, Zac as co-authors</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/MAAP-Project/maap-documentation/pull/459/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='1'/>

2024-11-14 20:11 UTC, omshinde commented on maapcopcguide (2).ipynb
> +{
<ol><li>Cloud-Optimized Point Cloud (COPC) format on the MAAP ADE -&gt; Cloud-Optimized Point Cloud (COPC) format in the MAAP ADE</li><li>Within your Jupyter Notebook, start by importing the maap package. Then invoke the MAAP constructor, setting the maap_host argument to 'api.ops.maap-project.org'.. Maybe have <code>maap_host</code> and <code>api.ops.maap-project.org</code> as inline code blocks.   </li><li>Replace <code>api.ops.maap-project.org</code> by <code>api.maap-project.org</code>   <span class="ql-cursor">﻿</span></li></ol>
<br/>

 _Reply via <a href='https://app.reviewnb.com/MAAP-Project/maap-documentation/pull/459/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='2'/>

2024-11-14 20:11 UTC, omshinde commented on maapcopcguide (2).ipynb
> +{
<p>Replace&nbsp;<code>api.ops.maap-project.org</code>&nbsp;by&nbsp;<code>api.maap-project.org</code></p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/MAAP-Project/maap-documentation/pull/459/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='3'/>

2024-11-14 20:11 UTC, omshinde commented on maapcopcguide (2).ipynb
> +{
<ol><li>search_data -&gt; <code>search_data</code></li><li>The temporal argument defines the temporal range for... Is that an incomplete sentence?</li></ol><p> </p><p> </p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/MAAP-Project/maap-documentation/pull/459/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='4'/>

2024-11-14 20:11 UTC, omshinde commented on maapcopcguide (2).ipynb
> +{
<p>valid_pipe.arrays -&gt; <code>valid_pipe.arrays</code></p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/MAAP-Project/maap-documentation/pull/459/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='17'/>

2024-11-14 21:17 UTC, rtapella commented
the file name is `maapcopcguide (2).ipynb`
that is probably not intentional?

2024-11-14 21:18 UTC, rtapella commented
also you may need to update a table-of-contents file somewhere to link this in, unless it's a direct update

2024-11-15 03:27 UTC, omshinde approved these changes
Thanks for your contribution.

2024-11-15 11:03 UTC, chuckwondo commented on docs/source/technical_tutorials/access/copc_access.ipynb
> +{
<p>The text does not match the code. Your code is using maap-py, not earthaccess.</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/MAAP-Project/maap-documentation/pull/459/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='4'/>

2024-11-15 11:03 UTC, chuckwondo commented on docs/source/technical_tutorials/access/copc_access.ipynb
> +{
<p>This output doesn't make sense. Where did this come from? I'm pretty sure that <code>maap.searchGranule</code> doesn't generate this output, but perhaps I'm mistaken and it has recently changed to produce it. </p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/MAAP-Project/maap-documentation/pull/459/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='7'/>

2024-11-15 11:03 UTC, chuckwondo commented on docs/source/technical_tutorials/access/copc_access.ipynb
> +{
<p>This output doesn't appear to match the code. <code>maap.downloadGranule</code> does not produce such output, but <code>earthaccess.download</code> does. Am I missing something? Did maap-py change to use earthaccess under the covers?  </p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/MAAP-Project/maap-documentation/pull/459/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='10'/>

2024-11-15 11:03 UTC, chuckwondo commented on docs/source/technical_tutorials/access/copc_access.ipynb
> +{
<p>There appears to be a missing step. I don't see where you converted the las file to a laz file. You have downloaded the las file above, but below the laz file has magically appeared without any conversion step.</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/MAAP-Project/maap-documentation/pull/459/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='11'/>

2024-11-15 11:03 UTC, chuckwondo commented on docs/source/technical_tutorials/access/copc_access.ipynb
> +{
<p>It looks like you created this notebook based upon this one: <a href="https://guide.cloudnativegeo.org/copc/lidar-las-to-copc.html" target="_blank">https://guide.cloudnativegeo.org/copc/lidar-las-to-copc.html</a></p><p> </p><p>However, this notebook appears to be missing several steps and uses maap-py, but describes earthaccess instead.</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/MAAP-Project/maap-documentation/pull/459/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='20'/>

2024-11-15 11:07 UTC, chuckwondo requested changes
In addition to my ReviewNB comments, I have a very minor markdown suggestion: remove boldface from headings. Headings should already be rendered as a heavier font, so there's no need to explicitly add boldfacing.

For example, `## **Run This Notebook**` should simply be `## Run This Notebook`.

Further, remove the `****` from around the title and simply use a leading single hash: `# Working with LiDAR ...`

2025-01-08 18:36 UTC, closed without merging