MAAP onboarding guide
MAAP-Project/maap-documentation pull request #60
Opened 2021-06-07 20:41 UTC by bsatoriu

This PR is for the new onboarding doc: https://github.com/MAAP-Project/maap-documentation/blob/getting-started/docs/source/getting_started.ipynb 

@gchang @abarciauskas-bgse  I wanted to include the following text regarding the approval process, but wasn't sure if we had a support email. Is there an email address we can use here?

> At this point, a MAAP administrator will approve your account which will grant you access to the MAAP ADE. This process typically takes 5-10 minutes. To check on the status of your pending account, contact the MAAP team at **support@maap-project.org**.

2021-06-07 20:46 UTC, gchang commented
Looks good, however, if someone followed the doc verbatim today, they would end up on the pilot ops site (but registering on Ops URS, which wouldn't work). I think we can release the doc today with it pointing to "*.ops.maap-project.org" ade and repo link, noting that this is temporary for now and update the docs later when we migrate hostnames.

2021-06-07 21:23 UTC, gchang commented
The changes are good! @spa0002 any issues, stylistic or otherwise, with integrating it into readthedocs?

Also with the email, @abarciauskas-bgse, can we set up a support@maap-project.org email and forward it to multiple people?

2021-06-08 19:19 UTC, spa0002 requested changes
Looks good. Recommend editing the index.rst file in the source directory so that the MAAP onboarding guide will appear in the table of contents. The table of contents is expected to change but for now can add the file name under the first `toctree` in index.rst file. For ex:

`Welcome to the MAAP User Documentation!
=======================================

.. toctree::
  :maxdepth: 2
  
  welcome.ipynb
  getting_started.ipynb
  git_clone_repo.ipynb`

Also, two minor edits recommended.

2021-06-08 19:19 UTC, spa0002 commented on docs/source/getting_started.ipynb
> +    "On your profile page, click the \"Choose File\" button to upload your key,\n",
Recommend changing comma to period at the end of the sentence.

2021-06-08 19:19 UTC, spa0002 commented on docs/source/getting_started.ipynb
> +   "cell_type": "code",
Appears there is an empty code block at the end of the page.

2021-06-08 20:45 UTC, bsatoriu commented
@spa0002 thanks for the comments! Just committed those updates.

2021-06-08 22:31 UTC, spa0002 approved these changes

2021-06-08 22:33 UTC, merged